application test clean
douyu/jupiter pull request #254
Opened 2021-08-19 08:12 UTC by yinzhicheng66

### Describe what this PR does / why we need it
application test clean

### Does this pull request fix one issue?

### Describe how you did it
add app.stop recive chan

### Describe how to verify it

### Special notes for reviews

2021-08-19 11:12 UTC, hnlq715 commented on pkg/pkg.go
> +func UUID() string {
这个id可以去掉

2021-08-19 11:13 UTC, hnlq715 commented on pkg/pkg.go
> +func UUID() string {
和appInstance 是一个意思

2021-08-20 09:03 UTC, hnlq715 requested changes
去掉UUID，用EnvAppInstance

2021-08-20 09:50 UTC, yinzhicheng66 commented on pkg/pkg.go
> +func UUID() string {
UUID has been replaced by appInstance.
thx

2021-08-23 05:41 UTC, hnlq715 approved these changes
LGTM~

2021-08-23 05:41 UTC, merged