Feat#336  add cache and clean features
douyu/jupiter pull request #337
Opened 2022-05-18 07:07 UTC by ywanbing

### Describe what this PR does / why we need it

### Does this pull request fix one issue?

### Describe how you did it

### Describe how to verify it

### Special notes for reviews

2022-05-18 07:55 UTC, hnlq715 requested changes

2022-05-18 07:55 UTC, hnlq715 commented on cmd/jupiter/internal/cmd/cmd_new.go
已存在的情况，也还需要尝试更新下模板

2022-05-18 07:55 UTC, hnlq715 commented on cmd/jupiter/internal/cmd/cmd_new.go
> +		cmd := exec.Command("git", "clone", gitPath, tempPath, "-b", "main", "--depth=1")
这里可能需要把--depth=1去掉

2022-05-18 07:55 UTC, hnlq715 commented on cmd/jupiter/internal/cmd/cmd.go
> +				Name:  "refresh",
这里就叫clean吧，支持清除缓存，clean+new就是refresh了

2022-05-18 07:55 UTC, hnlq715 commented on cmd/jupiter/internal/cmd/cmd.go
> +				Name:  "refresh",
考虑提供一个独立的clean操作，可能会更好，方便后期其他的配置或者缓存的清理

2022-05-18 08:14 UTC, ywanbing commented on cmd/jupiter/internal/cmd/cmd_new.go
如果已经存在，也尝试拉取模板，这缓存不就没有意义了吗？

2022-05-18 08:42 UTC, hnlq715 commented on cmd/jupiter/internal/cmd/cmd_new.go
不然模板会一直不更新呀，可以考虑根据文件变更时间决定，比如超过1天就更新下，pull增量的部分比全量pull还是会快很多

2022-05-18 08:42 UTC, hnlq715 commented on cmd/jupiter/internal/cmd/cmd_new.go
另一个思路是，让用户确认是否更新模板，可以参考oh-my-zsh的玩法 :-)

2022-05-18 08:43 UTC, hnlq715 commented on cmd/jupiter/internal/cmd/cmd_new.go
这样可以不只是更新模板，还可以更新下脚手架本身

2022-05-18 08:52 UTC, ywanbing commented on cmd/jupiter/internal/cmd/cmd_new.go
👌

2022-05-18 09:09 UTC, ywanbing commented on cmd/jupiter/internal/cmd/cmd_new.go
> +		cmd := exec.Command("git", "clone", gitPath, tempPath, "-b", "main", "--depth=1")
模板采用这种方式，应该是可以的；不用把全部的git内容都拉下来吧？
在全部拉取的过程中，对于网速慢的需要等待较长的时间。

2022-05-18 09:31 UTC, hnlq715 commented on cmd/jupiter/internal/cmd/cmd_new.go
> +		cmd := exec.Command("git", "clone", gitPath, tempPath, "-b", "main", "--depth=1")
嗯，需要考虑这样能不能正常更新

2022-05-18 09:37 UTC, ywanbing commented on cmd/jupiter/internal/cmd/cmd_new.go
> +		cmd := exec.Command("git", "clone", gitPath, tempPath, "-b", "main", "--depth=1")
这个可以通过后面的使用情况，再来看是否会存在问题。

2022-05-18 12:16 UTC, hnlq715 commented on cmd/jupiter/internal/cmd/cmd_new.go
> +		cmd := exec.Command("git", "clone", gitPath, tempPath, "-b", "main", "--depth=1")
ok

2022-05-19 09:40 UTC, hnlq715 approved these changes

2022-05-19 09:40 UTC, merged