add auto upgrade(#341)
douyu/jupiter pull request #345
Opened 2022-05-21 04:16 UTC by ywanbing

### Describe what this PR does / why we need it

### Does this pull request fix one issue?

### Describe how you did it

### Describe how to verify it

### Special notes for reviews

2022-05-26 02:53 UTC, hnlq715 commented
目前这个方案每次都需要请求github，是不是可以考虑基于修改时间来做提示，让用户自己选择是否更新模板呢

如下
<img width="423" alt="截屏2022-05-26 10 53 28" src="https://user-images.githubusercontent.com/1734615/170406026-dee1b5cd-cef2-41de-a274-f7ba9e404775.png">

2022-05-26 03:14 UTC, ywanbing commented
> 目前这个方案每次都需要请求github，是不是可以考虑基于修改时间来做提示，让用户自己选择是否更新模板呢
> 
> 如下 <img alt="截屏2022-05-26 10 53 28" width="423" src="https://user-images.githubusercontent.com/1734615/170406026-dee1b5cd-cef2-41de-a274-f7ba9e404775.png">

如果通过修改时间来判断，还是会去拉取github的信息来判断是否有内容更新，所以效果其实都是一样的。
对于让用户手动确认更新，倒是不错的选择。

2022-05-26 03:20 UTC, hnlq715 commented
> > 目前这个方案每次都需要请求github，是不是可以考虑基于修改时间来做提示，让用户自己选择是否更新模板呢
> > 如下 <img alt="截屏2022-05-26 10 53 28" width="423" src="https://user-images.githubusercontent.com/1734615/170406026-dee1b5cd-cef2-41de-a274-f7ba9e404775.png">
> 
> 如果通过修改时间来判断，还是会去拉取github的信息来判断是否有内容更新，所以效果其实都是一样的。 对于让用户手动确认更新，倒是不错的选择。
> 
> 加上修改时间来判断，好像是每天的第一次才会去检查是否需要更新。后面每次运行一直都不会存在 github 的请求，因为今天已经检查过更新了。

嗯，是这个意思，尽量避免每次都要访问github。

2022-06-08 02:39 UTC, hnlq715 requested changes

2022-06-08 02:39 UTC, sysulq commented on cmd/jupiter/internal/cmd/cmd_new.go
>  		if err := cleanTempLayout(); err != nil {
如果需要更新的话，应该是直接git pull就好呀

2022-06-08 02:39 UTC, sysulq commented on cmd/jupiter/internal/cmd/cmd_new.go
>  		if err := cleanTempLayout(); err != nil {
如果引入了更新的逻辑，这个clean的flag可以去掉了

2022-07-22 05:56 UTC, hnlq715 approved these changes

2022-07-22 05:56 UTC, merged