feat(freecache): v2 finish
douyu/jupiter pull request #702
Opened 2023-02-06 02:40 UTC by PengYechang

### Describe what this PR does / why we need it

### Does this pull request fix one issue?

### Describe how you did it

### Describe how to verify it

### Special notes for reviews

2023-02-08 02:52 UTC, hnlq715 requested changes

2023-02-08 02:52 UTC, sysulq commented on pkg/cache/xfreecache/v2/config.go
> +func DefaultConfig() Config {
Config统一都用*Config

2023-02-08 02:52 UTC, sysulq commented on pkg/cache/xfreecache/v2/config.go
> +func (c Config) SetName(name string) Config {
这些Set方法可以先去掉，变量已经export出来了，后面有必要再加呢？

2023-02-08 02:52 UTC, sysulq commented on pkg/cache/xfreecache/v2/localcache.go
> +	req Config
req->config

2023-02-08 02:52 UTC, hnlq715 commented on pkg/cache/xfreecache/v2/cache_test.go
> +	oneCache := NewLocalCache[string, Student](DefaultConfig().
有没有可能把API设计为DefaultConfig().Build()? 和其他组件的API保持一致

2023-02-08 11:22 UTC, hnlq715 requested changes

2023-02-08 11:22 UTC, hnlq715 commented on pkg/cache/xfreecache/v2/size.go
> +func ParseSize(s string) (Size, error) {
这个方法需要补充单测，或者考虑用其他的开源库也可以

2023-02-08 11:22 UTC, hnlq715 commented on pkg/cache/xfreecache/v2/config.go
> +			size = 256 * MB
也可以限制下最大内存

2023-02-08 11:22 UTC, hnlq715 commented on pkg/cache/xfreecache/v2/config.go
> +		innerCache = freecache.NewCache(int(size))
这个NewCache可以在解析完配置之后再做，DefaultConfig只设置默认配置

2023-02-08 11:22 UTC, hnlq715 commented on pkg/cache/xfreecache/v2/size.go
> +func ParseSize(s string) (Size, error) {
https://github.com/docker/go-units 比如这个

2023-02-08 11:22 UTC, hnlq715 commented on pkg/cache/xfreecache/v2/cache.go
> +		data, innerErr := json.Marshal(cacheData)
这个是否判断下，如果是proto.Message，就用proto来编解码

2023-02-08 11:22 UTC, hnlq715 commented on pkg/cache/xfreecache/v2/cache.go
> +		data, innerErr := json.Marshal(cacheData)
可以加个benchmark对比下proto和json两种对象的性能

2023-02-14 01:57 UTC, hnlq715 requested changes
可以统一格式化下import的路径，然后我这边就没问题了

2023-02-14 01:57 UTC, hnlq715 commented on pkg/cache/xfreecache/v2/cache.go
> +	idsNone := make([]K, 0)
这里可以考虑预分配len(ids)的内存

2023-02-14 01:57 UTC, hnlq715 commented on pkg/cache/xfreecache/v2/cache.go
> +			if msg, ok := any(value).(proto.Message); ok { // Constrained to proto.Message
可以考虑封装下unmarshal和marshal的方法，参数是any

2023-02-15 02:45 UTC, miaofeng2027 approved these changes

2023-02-17 11:00 UTC, hnlq715 approved these changes

2023-02-17 11:00 UTC, sysulq commented on pkg/cache/xfreecache/v2/encode.go
> +		msg = reflect.New(msgType).Interface().(proto.Message)
这里可以用sync.Pool缓存一下，对比看看

2023-02-17 11:01 UTC, merged