update xecho access log with trace id
douyu/jupiter pull request #889
Opened 2023-05-23 06:59 UTC by 5idu

### Describe what this PR does / why we need it
There is no trace id field in the `xecho access log`, but we do need it.

### Describe how you did it
Just replace the default logger in the middleware

### Describe how to verify it
The trace id field is included in the output access log

2023-05-26 07:16 UTC, hnlq715 requested changes

2023-05-26 07:16 UTC, hnlq715 commented on pkg/server/xecho/middleware.go
> +				logger := xlog.FromContext(ctx.Request().Context())
这里FromContext取的是default log，这个主要是用于业务日志，建议用Jupiter()日志，写入系统日志

2023-07-31 06:16 UTC, 5idu commented
@hnlq715 麻烦看下，这个 PR 已经好久了

2023-07-31 08:38 UTC, hnlq715 requested changes

2023-07-31 08:38 UTC, sysulq commented on pkg/server/xecho/middleware.go
> +			ctx = xlog.NewContext(ctx, xlog.Jupiter(), span.SpanContext().TraceID().String())
可以考虑把jupiter和default日志都注入到ctx，然后框架用xlog.J(ctx)，业务项目用xlog.L(ctx)来获取对应日志实例

@5idu

2023-08-01 08:30 UTC, hnlq715 requested changes

2023-08-01 08:30 UTC, sysulq commented on pkg/xlog/context.go
> +func NewContextWithDefaultLogger(ctx context.Context, l *Logger, traceID string) context.Context {
这里尽量保证兼容，不改API

2023-08-01 08:30 UTC, hnlq715 commented on pkg/xlog/context.go
> +func NewContextWithJupiterLogger(ctx context.Context, l *Logger, traceID string) context.Context {
这里新增的这个api可以不export出来，用newContextWithJupiterLogger

2023-08-01 08:30 UTC, sysulq commented on pkg/xlog/context.go
> +func GetDefaultLoggerFromContext(ctx context.Context) *Logger {
同上

2023-08-01 08:30 UTC, sysulq commented on pkg/xlog/context.go
> +func GetJupiterLoggerFromContext(ctx context.Context) *Logger {
同上

2023-08-02 02:42 UTC, hnlq715 requested changes

2023-08-02 02:42 UTC, hnlq715 commented on pkg/xlog/context.go
> +func newContextWithJupiterLogger(ctx context.Context, l *Logger, traceID string) context.Context {
这个FromContext还是可以继续保留API，可以加个Deprecated注释，推荐使用xlog.L

2023-08-15 06:35 UTC, hnlq715 approved these changes

2023-08-15 06:36 UTC, merged