Feat/add redis cluster
douyu/jupiter pull request #938
Opened 2023-07-27 11:52 UTC by city55238

### Describe what this PR does / why we need it
redis支持集群模式
### Does this pull request fix one issue?

### Describe how you did it
在原生redis-go sdk的基础上接入cluster,修改cluster redis配置的加载方式

cluster配置支持云厂商连接："r-bp1zxszhcgatnx****.redis.rds.aliyuncs.com:6379"

也支持自定义node集群连接： ["127.0.0.1:6379","127.0.0.1:6370","127.0.0.1:6371"]

配置示例：
[jupiter.redis.exampleserver]
[jupiter.redis.exampleserver.stub]
debug = false
maxIdle = 10
maxActive = 50
dialTimeout = "2s"
readTimeout = "2s"
idleTimeout = "60s"
enableAccessLog = false
[jupiter.redis.exampleserver.stub.cluster]
addr = ["r-bp1zxszhcgatnx****.redis.rds.aliyuncs.com:6379"] # ["127.0.0.1:6379","127.0.0.1:6370","127.0.0.1:6371"]
user = "root"
password = "xxxxxx"
### Describe how to verify it

### Special notes for reviews

2023-07-28 01:59 UTC, hnlq715 commented
建议新增一种cluster类型，和stub类型同级

2023-07-31 09:07 UTC, hnlq715 commented
@city55238 我理解的，是不是把cluster和stub client完全独立会更好呢？

2023-07-31 10:37 UTC, city55238 commented
> 

redis stub模式也是在第二层的，我理解cluster也应该是在这个位置
![image](https://github.com/douyu/jupiter/assets/59048617/5070b932-0ab5-48f6-8e82-4eab48c2728b)

2023-08-08 03:00 UTC, hnlq715 commented
@city55238 可以参考现有的redis单测，加下cluster的测试用例

2023-08-08 07:44 UTC, city55238 commented
> 
已经补充过了，但是nomal start的样例需要你那边有一个集群模式的redis，不然单测跑不过

2023-08-09 05:53 UTC, hnlq715 requested changes

2023-08-09 05:53 UTC, sysulq commented on pkg/client/redis/cluster.go
> +
这里如果用组合会不会更简单些

```
type ClusterClient struct {
	*redis.ClusterClient
	config  *Config
}
```

2023-08-09 05:53 UTC, sysulq commented on pkg/client/redis/cluster.go
> +func (ins *ClusterClient) CmdOnCluster() *redis.ClusterClient {
如果是用组合的话，这个方法就不需要了

2023-08-09 05:53 UTC, sysulq commented on pkg/client/redis/cluster_test.go
> +		err = client.cluster.Ping(context.Background()).Err()
这里应该直接是client.Ping

2023-08-09 05:53 UTC, hnlq715 commented on pkg/client/redis/cluster.go
> +	cluster *redis.ClusterClient
这一行也可以去掉了

2023-08-09 05:53 UTC, hnlq715 commented on pkg/client/redis/config.go
> +	Addr     []string `json:"addr" toml:"addr"`
感觉配置这块最好也另外加个struct，避免因为误用接口，比如想要BuildCluster，但是用了Build，导致启动失败之类？

2023-08-09 06:34 UTC, city55238 commented on pkg/client/redis/config.go
> +	Addr     []string `json:"addr" toml:"addr"`
配置区分开的话，钩子函数这一块也得改，就有点像另一个package了

![image](https://github.com/douyu/jupiter/assets/59048617/f42eec8c-2598-4889-a007-da077dde4ad2)

2023-08-10 11:07 UTC, hnlq715 requested changes

2023-08-10 11:07 UTC, hnlq715 commented on pkg/client/redis/cluster_config.go
> +func DefaultOption() *ClusterOptions {
这里应该是DefaultClusterOption？

2023-08-10 11:07 UTC, hnlq715 commented on pkg/client/redis/config_test.go
> +				assert.Equal(t, r.(string), "no cluster master or slaves addr set:jupiter.redis.test.stub")
这里可以回滚下

2023-08-11 02:12 UTC, hnlq715 approved these changes

2023-08-11 02:13 UTC, hnlq715 commented
LGTM

2023-08-11 02:13 UTC, merged